on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: sebtestorg2/renovate-clean
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # tag=v1.7.0
        with:
          app_id: ${{ secrets.SEB_RENOVATE_APP_ID }}
          installation_id: ${{ secrets.SEB_RENOVATE_INSTALL_ID }}
          private_key: ${{ secrets.SEB_RENOVATE_PRIVATE_KEY }}
      - name: Create branch, commit and push
        id: branch
        run: |
          BRANCH="githubaction-go-generate-$(date +%Y-%m-%d-%H-%M-%S)"
          echo "::set-output name=branch::$BRANCH"
          git config --global user.email "118825710+renovate-action[bot]@users.noreply.github.com"
          git config --global user.name "renovate-action[bot]"
          git checkout -b "$BRANCH"
          echo "blaat" > blaat
          git add blaat
          git commit -a -m 'blaat'
          git push https://x-access-token:$CUSTOM_TOKEN@github.com/sebtestorg2/renovate-clean.git $BRANCH
          #gh pr create -R sebtestorg2/renovate-clean --title "The bug is fixed" --body "Everything works again" --base main --head $BRANCH
        env:
          CUSTOM_TOKEN: '${{ steps.get_token.outputs.token }}'
