name: Deploy Renovate
on:
  workflow_dispatch:
    inputs:
      deployRepository:
        description: "The repository to deploy Renovate to"
        required: true
        default: "sebtestorg2/"
        type: string
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # tag=v1.7.0
        with:
          app_id: ${{ secrets.SEB_RENOVATE_APP_ID }}
          installation_id: ${{ secrets.SEB_RENOVATE_INSTALL_ID }}
          private_key: ${{ secrets.SEB_RENOVATE_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          path: main
      - name: Checkout deploy repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: '${{ github.event.inputs.deployRepository }}'
          token: '${{ steps.get_token.outputs.token }}'
          path: deploy-repo
      - name: Create branch, commit and push
        id: branch
        run: |
          BRANCH="githubaction-test-$(date +%Y-%m-%d-%H-%M-%S)"
          git config --global user.email "118825710+renovate-action[bot]@users.noreply.github.com"
          git config --global user.name "renovate-action[bot]"
          cd deploy-repo
          DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
          git checkout -b "$BRANCH"
          TEMP_CONFIG=$(mktemp)
          jq --arg default_branch "$DEFAULT_BRANCH" '.baseBranches = [$default_branch]' ../main/files/blaat > $TEMP_CONFIG
          mkdir files
          mv $TEMP_CONFIG files/blaat 
          git add files/blaat
          if [ -f .github/dependabot.yaml ]; then
            git rm .github/dependabot.yaml
          fi
          git commit -a -m 'blaat'
          git push origin $BRANCH
          gh pr create -R $DEPLOY_REPOSITORY --title "Adding blaat" --body ":smile:, initiated by @$GITHUB_ACTOR" --base $DEFAULT_BRANCH --head $BRANCH
          BODY="Blablabla; \
          \`ab\` -> \`cd\` -> \
          \`ef\` g ->
          \`hi\` -> Add \`j-k\` -> \`lm\`"                                                                                                                                                                                                                  
          gh issue create --title "Onboarding Renovate for repository ${DEPLOY_REPOSITORY}" --body "${BODY}" --repo sebtestorg2/control
        env:
          DEPLOY_REPOSITORY: '${{ github.event.inputs.deployRepository }}'
          GITHUB_TOKEN: '${{ steps.get_token.outputs.token }}'
